# Generated by Django 4.2.21 on 2025-06-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
