# Generated by Django 4.2.21 on 2025-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
