# Generated by Django 5.2.1 on 2025-06-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
